services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:latest  
    container_name: wireguard
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.69.69.0/24
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    ports:
      - 51820:51820/udp
    restart: unless-stopped
