version: '3.3'

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:latest
    container_name: wireguard-client
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    network_mode: "host"
